"""Render dist/ artifacts. Owns the register wrapper constants so gate.py can
parse generated content back to JSON through the same seam (no desync).
"""
import json
import shutil

from .determinism import canonical_json

REGISTER_PREFIX = "/* generated by build.py — do not edit */\nSTUDY.register(\n"
REGISTER_SUFFIX = "\n);\n"

SHELL_FILES = [
    "index.html", "app/loader.js", "app/cards.js", "app/study.js", "app/pwa.js",
    "app/ui.css", "app/icon.svg",
]


def render_content(envelope):
    return REGISTER_PREFIX + canonical_json(envelope) + REGISTER_SUFFIX


def parse_content(js_text):
    """Inverse of render_content — used by the gate to read built items back."""
    inner = js_text
    if inner.startswith(REGISTER_PREFIX):
        inner = inner[len(REGISTER_PREFIX):]
    if inner.endswith(REGISTER_SUFFIX):
        inner = inner[: -len(REGISTER_SUFFIX)]
    return json.loads(inner)


def render_manifest(content_relpaths):
    files = ", ".join(f'"./{p}"' for p in content_relpaths)
    return (
        "/* generated by build.py — do not edit */\n"
        f"STUDY.expect({len(content_relpaths)});\n"
        f"STUDY.use([{files}]);\n"
    )


def render_webmanifest():
    return canonical_json({
        "name": "secstudy — Security Study Platform",
        "short_name": "secstudy",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "background_color": "#0f1419",
        "theme_color": "#0f1419",
        "icons": [
      {"src": "./app/icon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "any maskable"},
    ],
    }) + "\n"


def render_sw(cache_version, precache_relpaths):
    files = ",\n  ".join(f'"./{p}"' for p in sorted(precache_relpaths))
    return (
        "/* generated by build.py — do not edit */\n"
        f'const CACHE = "{cache_version}";\n'
        "const PRECACHE = [\n"
        '  "./",\n'
        f"  {files}\n"
        "];\n"
        'self.addEventListener("install", (e) => {\n'
        "  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));\n"
        "});\n"
        'self.addEventListener("activate", (e) => {\n'
        "  e.waitUntil(caches.keys()\n"
        "    .then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))\n"
        "    .then(() => self.clients.claim()));\n"
        "});\n"
        'self.addEventListener("fetch", (e) => {\n'
        '  if (e.request.method !== "GET") return;\n'
        "  e.respondWith(caches.match(e.request).then((r) => r || fetch(e.request)));\n"
        "});\n"
    )


def copy_shell(repo_root, dist_dir):
    """Copy the app shell into dist/. Returns the list of files not yet present
    (empty once D6 lands; lets C5 be verified before the app exists)."""
    missing = []
    for rel in SHELL_FILES:
        src = repo_root / rel
        dst = dist_dir / rel
        if src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)
        else:
            missing.append(rel)
    return missing
