/* generated by build.py — do not edit */
const CACHE = "secstudy-0849e74b33cd";
const PRECACHE = [
  "./",
  "./app/cards.js",
  "./app/icon.svg",
  "./app/loader.js",
  "./app/pwa.js",
  "./app/study.js",
  "./app/ui.css",
  "./content/aws-cloud-security.cards.js",
  "./index.html",
  "./manifest.js",
  "./manifest.webmanifest"
];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request).then((r) => r || fetch(e.request)));
});
